INSERT INTO `omik_polititablet_laws` (`id`, `type`, `law`, `paragraph`, `title`, `cols`) VALUES
(2, 'Law', 'Færdselsloven', NULL, NULL, '{\"Pris\":0,\"Klip\":0,\"Frakendelse\":false}'),
(3, 'Offense', 'Færdselsloven', 'FL. §4, stk. 1', 'Kørsel frem mod rødt lyssignal', '{\"Pris\":2500,\"Klip\":1,\"Frakendelse\":false}'),
(4, 'Offense', 'Færdselsloven', 'FL. §4, stk. 1', 'Færdselstavle eller pile ikke respekteret', '{\"Pris\":1500,\"Klip\":0,\"Frakendelse\":false}'),
(5, 'Offense', 'Færdselsloven', 'FL. §4, stk. 1', 'Kørsel mod kørselsretning', '{\"Pris\":2500,\"Klip\":1,\"Frakendelse\":false}'),
(6, 'Offense', 'Færdselsloven', 'FL. §4, stk. 1', 'Overskredet spærrelinie ved overhaling', '{\"Pris\":2000,\"Klip\":1,\"Frakendelse\":false}'),
(7, 'Offense', 'Færdselsloven', 'FL. §6, stk. 1', 'Springe på eller hage sig fast i køretøj m.v./ophold på trinbræt', '{\"Pris\":700,\"Klip\":0,\"Frakendelse\":false}'),
(8, 'Offense', 'Færdselsloven', 'FL. §10, skt.  1-2 og 4-6', 'Færden over eller langs kørebanen m.v. (Ikke benytte fortov, fodgængerfelt m.v.)', '{\"Pris\":700,\"Klip\":0,\"Frakendelse\":false}'),
(9, 'Offense', 'Færdselsloven', 'FL. §15, stk. 1', 'Unladt at holde så langt til højre som muligt', '{\"Pris\":1500,\"Klip\":0,\"Frakendelse\":false}'),
(10, 'Offense', 'Færdselsloven', 'FL. §15, stk. 4', 'Unladt at køre højre om helleanlæg', '{\"Pris\":2500,\"Klip\":1,\"Frakendelse\":false}'),
(11, 'Offense', 'Færdselsloven', 'FL. §21, stk. 1', 'Foretaget overhaling højre om', '{\"Pris\":2500,\"Klip\":1,\"Frakendelse\":false}'),
(12, 'Offense', 'Færdselsloven', 'FL. §26, stk. 2', 'Ubetinget vigepligt (fuldt stop)', '{\"Pris\":2500,\"Klip\":1,\"Frakendelse\":false}'),
(13, 'Offense', 'Færdselsloven', 'FL. §28, stk. 4', 'Undladt at sikre køretøj', '{\"Pris\":1000,\"Klip\":0,\"Frakendelse\":false}'),
(14, 'Offense', 'Færdselsloven', 'FL. §33, stk. 1', 'Motorkøretøj eller knallert uden tændte lygter i lygtetændingstiden', '{\"Pris\":1000,\"Klip\":0,\"Frakendelse\":false}'),
(15, 'Offense', 'Færdselsloven', 'FL. §38', 'Unødig støj/røg m.v. (burnout)', '{\"Pris\":1000,\"Klip\":0,\"Frakendelse\":false}'),
(16, 'Offense', 'Færdselsloven', 'FL. §55 a', 'Benyttet håndholdt mobiltelefon under kørsel', '{\"Pris\":1500,\"Klip\":1,\"Frakendelse\":false}'),
(17, 'Offense', 'Færdselsloven', 'FL. §67, stk. 2', 'Køretøjs mangel/fejl', '{\"Pris\":1000,\"Klip\":0,\"Frakendelse\":false}'),
(18, 'Offense', 'Færdselsloven', 'FL. §9', 'Kørsel firbi ulykkessted uden at hjælpe', '{\"Pris\":7500,\"Klip\":0,\"Frakendelse\":false}'),
(19, 'Offense', 'Færdselsloven', 'FL. §15', 'Kørsel med kort afstand til forankørende', '{\"Pris\":2000,\"Klip\":0,\"Frakendelse\":false}'),
(20, 'Offense', 'Færdselsloven', 'FL. §33 stk. 7', 'Motorkøretøj eller knallert uden tændte lygter i lygtetændingstiden', '{\"Pris\":1000,\"Klip\":0,\"Frakendelse\":false}'),
(21, 'Offense', 'Færdselsloven', 'FL. §37 stk. 4', 'Kap eller væddeløbskørsel på offentlig vej', '{\"Pris\":2500,\"Klip\":0,\"Frakendelse\":false}'),
(22, 'Offense', 'Færdselsloven', 'FL. §41', 'Hasarderet kørsel', '{\"Pris\":5000,\"Klip\":1,\"Frakendelse\":false}'),
(23, 'Offense', 'Færdselsloven', 'FL. §41 stk. 2', 'Uansvarlig kørsel', '{\"Pris\":10000,\"Klip\":3,\"Frakendelse\":true}'),
(24, 'Offense', 'Færdselsloven', 'FL. §53/54', 'Kørsel i påvirket tilstand', '{\"Pris\":1500,\"Klip\":0,\"Frakendelse\":true}'),
(25, 'Offense', 'Færdselsloven', 'FL. §56 stk. 1', 'Kørsel uden medbringelse af kørekort', '{\"Pris\":1000,\"Klip\":0,\"Frakendelse\":false}'),
(26, 'Offense', 'Færdselsloven', 'FL. §56 stk. 1', 'Kørsel i frakendelsestiden 1. gang', '{\"Pris\":7500,\"Klip\":0,\"Frakendelse\":false}'),
(27, 'Offense', 'Færdselsloven', 'FL. §56 stk. 1', 'Kørsel i frakendelsestiden 2. gang', '{\"Pris\":15000,\"Klip\":0,\"Frakendelse\":false}'),
(28, 'Offense', 'Færdselsloven', 'FL. §56 stk. 1', 'Kørsel i frakendelsestiden 3. gang', '{\"Pris\":30000,\"Klip\":0,\"Frakendelse\":false}'),
(29, 'Offense', 'Færdselsloven', 'FL. §56 stk. 1', 'Kørsel ude førerret 1. gang', '{\"Pris\":5000,\"Klip\":0,\"Frakendelse\":false}'),
(30, 'Offense', 'Færdselsloven', 'FL. §56 stk. 1', 'Kørsel ude førerret 2. gang', '{\"Pris\":10000,\"Klip\":0,\"Frakendelse\":false}'),
(31, 'Offense', 'Færdselsloven', 'FL. §56 stk. 1', 'Kørsel ude førerret 3. gang', '{\"Pris\":15000,\"Klip\":0,\"Frakendelse\":false}'),
(32, 'Offense', 'Færdselsloven', 'FL. §81', 'Fædsel uden styrthjelm', '{\"Pris\":1500,\"Klip\":0,\"Frakendelse\":false}'),
(33, 'Offense', 'Færdselsloven', 'FL. §65 stk. 1 /  §118 stk. 2', 'Oplysningspligten', '{\"Pris\":3000,\"Klip\":0,\"Frakendelse\":false}'),
(34, 'Offense', 'Færdselsloven', 'FL. §66 stk. 1', 'Tonede ruder', '{\"Pris\":2500,\"Klip\":0,\"Frakendelse\":false}'),
(35, 'Offense', 'Færdselsloven', 'FL. §67 stk. 1', 'Udlån af køretøj til borger uden kørekort', '{\"Pris\":5000,\"Klip\":0,\"Frakendelse\":false}'),
(36, 'Offense', 'Færdselsloven', 'FL. 4 stk. 2', ' Kørsel frem mod rødt lyssignal på cykel', '{\"Pris\":1250,\"Klip\":0,\"Frakendelse\":false}'),
(37, 'Offense', 'Færdselsloven', '§ 14 a.', 'Cykling i fodgængerfeltet, på fortov eller gangsti', '{\"Pris\":700,\"Klip\":0,\"Frakendelse\":false}'),
(38, 'Offense', 'Færdselsloven', '§ 14 b.', 'Kørsel uden lys i lygtetændingstiden', '{\"Pris\":700,\"Klip\":0,\"Frakendelse\":false}'),
(39, 'Offense', 'Færdselsloven', '§ 14 c.', 'Nægter at respektere skilte og afmærkning på cykel', '{\"Pris\":700,\"Klip\":0,\"Frakendelse\":false}'),
(40, 'Offense', 'Færdselsloven', '§ 14 d.', 'Benyttet håndholdt mobiltelefon under cykling', '{\"Pris\":1000,\"Klip\":0,\"Frakendelse\":false}'),
(41, 'Offense', 'Færdselsloven', '§ 14 d.', 'Overtræde ubetinget vigepligt/fuldt stop cykel', '{\"Pris\":1000,\"Klip\":0,\"Frakendelse\":false}'),
(42, 'Offense', 'Færdselsloven', '§ 14 d.', 'Uansvarlig kørsel på cykel, grundet påvirkning af euforiserende stoffer/alkohol', '{\"Pris\":2500,\"Klip\":0,\"Frakendelse\":false}'),
(43, 'Law', 'Straffeloven', NULL, NULL, '{\"Pris\":0,\"Fængselstid\":0,\"Kommentar\":\"\"}'),
(44, 'Offense', 'Straffeloven', 'SL. §199', 'Overfald på embedsmand', '{\"Pris\":20000,\"Fængselstid\":15,\"Kommentar\":\"Så snart en borger overfalder en embedsmand i funktion\"}'),
(45, 'Offense', 'Straffeloven', 'SL. §199', 'Trusler mod embedsmand', '{\"Pris\":10000,\"Fængselstid\":9,\"Kommentar\":\"Så snart en borger true en embedsmand i funktion\"}'),
(46, 'Offense', 'Straffeloven', 'SL. §121', 'Fornærmelser/krænkelser mod embedsmand', '{\"Pris\":3500,\"Fængselstid\":0,\"Kommentar\":\"Så snart en person fornærmer/krænker dig\"}'),
(47, 'Offense', 'Straffeloven', 'SL. §122', 'Forrsøgt bestikkelse af politiet', '{\"Pris\":10000,\"Fængselstid\":5,\"Kommentar\":\"Så snart en borger yder, lover eller tilbyder politiet i bytte for at undlade tjenesten.\"}'),
(48, 'Offense', 'Straffeloven', 'SL. §134 b', 'Maskering', '{\"Pris\":2500,\"Fængselstid\":0,\"Kommentar\":\"Så snart en boreger bærer maskering i offentligheden\"}'),
(49, 'Offense', 'Straffeloven', 'SL. §135', 'Misbrug af nødopkald', '{\"Pris\":1500,\"Fængselstid\":5,\"Kommentar\":\"Så snart en borger ugrundet kontakter politi, ambulance, redningsberedskabet sø- eller luftredninstjenesten\"}'),
(50, 'Offense', 'Straffeloven', 'SL. §162', 'Falske anklager', '{\"Pris\":7500,\"Fængselstid\":5,\"Kommentar\":\"Så snart folk afgiver en falsk ifm. en anmeldelse.\"}'),
(51, 'Offense', 'Straffeloven', 'SL. §172', 'Identifikations forfalskning', '{\"Pris\":10000,\"Fængselstid\":5,\"Kommentar\":\"Så snart en borger dokumentforfalsker/forfalsker sit navn eller andet\"}'),
(52, 'Offense', 'Straffeloven', 'SL. §237', 'Mord', '{\"Pris\":40000,\"Fængselstid\":40,\"Kommentar\":\"Så snart en borger dræber en anden\"}'),
(53, 'Offense', 'Straffeloven', 'SL. §237', 'Mordforsøg', '{\"Pris\":30000,\"Fængselstid\":15,\"Kommentar\":\"Så snart en borger prøver, at dræbe en anden, men det ikke lykkes\"}'),
(54, 'Offense', 'Straffeloven', 'SL. §237', 'Mord på embedsmand', '{\"Pris\":50000,\"Fængselstid\":45,\"Kommentar\":\"Så snart en borger dræber en embedsmand i funktion\"}'),
(55, 'Offense', 'Straffeloven', 'SL. §237', 'Mordforsøg på embedsmand', '{\"Pris\":35000,\"Fængselstid\":20,\"Kommentar\":\"Så snart en borger prøver, at myrde en embedsmand i funktion, men det ikke lykkes\"}'),
(56, 'Offense', 'Straffeloven', 'SL. §241', 'Uagtsomt manddrab', '{\"Pris\":20000,\"Fængselstid\":15,\"Kommentar\":\"Så snart en borger uagtsomt forvolder en andens død\"}'),
(57, 'Offense', 'Straffeloven', 'SL. §244', 'Overfald', '{\"Pris\":15000,\"Fængselstid\":10,\"Kommentar\":\"Så snart en borger overfalder en anden\"}'),
(58, 'Offense', 'Straffeloven', 'SL. §244', 'Overfald på borger med flydende væsker', '{\"Pris\":5000,\"Fængselstid\":0,\"Kommentar\":\"Hvis der bliver overfaldet med flydemde væsker\"}'),
(59, 'Offense', 'Straffeloven', 'SL. §252', 'Sætte andre folks liv i fare', '{\"Pris\":10000,\"Fængselstid\":10,\"Kommentar\":\"Hvis en borger sætter andres liv i fare\"}'),
(60, 'Offense', 'Straffeloven', 'SL. §253', 'Flugt fra færdselsuheld', '{\"Pris\":5000,\"Fængselstid\":5,\"Kommentar\":\"Hvis en borger flygter fra et færdselsuheld\"}'),
(61, 'Offense', 'Straffeloven', 'SL. §261', 'Gidseltaging', '{\"Pris\":30000,\"Fængselstid\":15,\"Kommentar\":\"Så snart en borger tager en anden som gidsel\"}'),
(62, 'Offense', 'Straffeloven', 'SL. §261', 'Gidseltaging på embedsmand', '{\"Pris\":40000,\"Fængselstid\":20,\"Kommentar\":\"Så snart en borger tager en embedsmand som gidsel\"}'),
(63, 'Offense', 'Straffeloven', 'SL. §264', ' Ulovlig indtrængen', '{\"Pris\":10000,\"Fængselstid\":5,\"Kommentar\":\"Hvis en person befinder på private ejendomme\"}'),
(64, 'Offense', 'Straffeloven', 'SL. §266', 'Trusler', '{\"Pris\":7500,\"Fængselstid\":5,\"Kommentar\":\"Så snart en borger truer en anden\"}'),
(65, 'Offense', 'Straffeloven', 'SL. §288', 'Bankrøveri', '{\"Pris\":100000,\"Fængselstid\":50,\"Kommentar\":\"Så snart en borger røver en bank\"}'),
(66, 'Offense', 'Straffeloven', 'SL. §288', 'Butikstyveri', '{\"Pris\":20000,\"Fængselstid\":15,\"Kommentar\":\"Så snart en borger røver en butik\"}'),
(67, 'Offense', 'Straffeloven', 'SL. §289', 'Besiddelse af sorte penge', '{\"Pris\":0,\"Fængselstid\":0,\"Kommentar\":\"Konfiskere pengene\"}'),
(68, 'Offense', 'Straffeloven', 'SL. §291', 'Hæreværk', '{\"Pris\":5000,\"Fængselstid\":0,\"Kommentar\":\"Den, der ødelægger, beskadiger eller bortskaffer ting, der tilhører en anden\"}'),
(69, 'Offense', 'Straffeloven', 'SL. §293 a', 'Brugstyveri', '{\"Pris\":25000,\"Fængselstid\":15,\"Kommentar\":\"Så snart en borger brugstjæler et motorkøretøj\"}'),
(70, 'Offense', 'Straffeloven', '', 'Udeblivelse af fogedretten', '{\"Pris\":30000,\"Fængselstid\":10,\"Kommentar\":\"Kan bruges når folk bevist ikke møder op til en fogedretssag når de er indkaldt\"}'),
(71, 'Offense', 'Straffeloven', 'SL. §124', 'Flugt fra politiet', '{\"Pris\":25000,\"Fængselstid\":20,\"Kommentar\":\"\"}'),
(72, 'Offense', 'Straffeloven', 'SL. §252', 'Hensynsløs kørsel', '{\"Pris\":30000,\"Fængselstid\":20,\"Kommentar\":\"Hensynsløs kørsel i form af at sætte andre folks liv i fare\"}'),
(73, 'Offense', 'Straffeloven', '', 'Permanent beslaglæggelse af køretøj', '{\"Pris\":0,\"Fængselstid\":0,\"Kommentar\":\"Beslagløggelse af køretøj ved kørsel den føreret 3 gange og op\"}'),
(74, 'Offense', 'Straffeloven', 'SL. §232', 'Krænkende adfærd, herunder sexchikane', '{\"Pris\":15000,\"Fængselstid\":0,\"Kommentar\":\"\"}'),
(75, 'Offense', 'Straffeloven', 'SL. §288', 'Røveri mod pengetransport', '{\"Pris\":33000,\"Fængselstid\":15,\"Kommentar\":\"\"}'),
(76, 'Offense', 'Straffeloven', 'SL. §276', 'Inbrudstyveri', '{\"Pris\":10000,\"Fængselstid\":8,\"Kommentar\":\"For inbrudstyveri straffes den, som uberettiget skaffer sig adgang til fremmed hus uden besidderens samtykke borttager en fremmed rørlig ting for at skaffe sig eller andre uberettiget vinding ved dem tilegnelse\"}'),
(77, 'Law', 'Bek. euf. stoffer', NULL, NULL, '{\"Pris\":0,\"Fængselstid\":0,\"Kommentar\":\"\"}'),
(78, 'Offense', 'Bek. euf. stoffer', '', 'Besiddelse af Kokain', '{\"Pris\":650,\"Fængselstid\":10,\"Kommentar\":\"Til den som besidder Kokain (650 pr. stk)\"}'),
(79, 'Offense', 'Bek. euf. stoffer', '', 'Besiddelse af Heroin', '{\"Pris\":660,\"Fængselstid\":10,\"Kommentar\":\"Til den som besidder Heroin (650 pr. stk)\"}'),
(80, 'Offense', 'Bek. euf. stoffer', '', 'Besiddelse af Metamfetamin', '{\"Pris\":550,\"Fængselstid\":15,\"Kommentar\":\"Til den som besidder Metamfetamin (550 pr. stk)\"}'),
(81, 'Offense', 'Bek. euf. stoffer', '', 'Besiddelse af Joints', '{\"Pris\":650,\"Fængselstid\":15,\"Kommentar\":\"Til den som besidder Joints (650 pr. stk)\"}'),
(82, 'Offense', 'Bek. euf. stoffer', '', 'Besiddelse af Svampe', '{\"Pris\":175,\"Fængselstid\":0,\"Kommentar\":\"Til den som besidder Svampe (175 pr. stk)\"}'),
(83, 'Offense', 'Bek. euf. stoffer', '', 'Besiddelse af Opium', '{\"Pris\":300,\"Fængselstid\":0,\"Kommentar\":\"Til den som besidder Opium (300 pr. stk)\"}'),
(84, 'Offense', 'Bek. euf. stoffer', '', 'Besiddelse af Kokaplanter', '{\"Pris\":325,\"Fængselstid\":0,\"Kommentar\":\"Til den som besidder Kokaplanter (325 pr. stk)\"}'),
(85, 'Offense', 'Bek. euf. stoffer', '', 'Besiddelse af Amfetamin', '{\"Pris\":650,\"Fængselstid\":0,\"Kommentar\":\"Til den som besidder Amfetamin (650 pr. stk)\"}'),
(86, 'Offense', 'Bek. euf. stoffer', '', 'Besiddelse af Hash', '{\"Pris\":650,\"Fængselstid\":0,\"Kommentar\":\"Til den som besidder Hash (650 pr. stk)\"}'),
(87, 'Law', 'Våben & kniv loven', NULL, NULL, '{\"Pris\":0,\"Fængselstid\":0,\"Kommentar\":\"\"}'),
(88, 'Offense', 'Våben & kniv loven', 'VL. §1', 'Besiddelse af Assault Rifle', '{\"Pris\":500000,\"Fængselstid\":55,\"Kommentar\":\"Til den som besidder en Assault Rifle\"}'),
(89, 'Offense', 'Våben & kniv loven', 'VL. §1', 'Besiddelse af Compact Rifle', '{\"Pris\":250000,\"Fængselstid\":45,\"Kommentar\":\"Til den som besidder Compact Rifle\"}'),
(90, 'Offense', 'Våben & kniv loven', 'VL. §1', 'Besiddelse af Gussenberg', '{\"Pris\":250000,\"Fængselstid\":40,\"Kommentar\":\"Til den som besidder Gussenberg\"}'),
(91, 'Offense', 'Våben & kniv loven', 'VL. §1', 'Besiddelse af Micro SMG', '{\"Pris\":200000,\"Fængselstid\":35,\"Kommentar\":\"Til den som besidder Micro SMG\"}'),
(92, 'Offense', 'Våben & kniv loven', 'VL. §1', 'Besiddelse af Mini SMG', '{\"Pris\":200000,\"Fængselstid\":35,\"Kommentar\":\"Til den som besidder Mini SMG\"}'),
(93, 'Offense', 'Våben & kniv loven', 'VL. §1', 'Besiddelse af Tec-9', '{\"Pris\":200000,\"Fængselstid\":30,\"Kommentar\":\"Til den som besidder Tec-9\"}'),
(94, 'Offense', 'Våben & kniv loven', 'VL. §1', 'Besiddelse af Desert Eagle', '{\"Pris\":170000,\"Fængselstid\":30,\"Kommentar\":\"Til den som besidder Desert Eagle\"}'),
(95, 'Offense', 'Våben & kniv loven', 'VL. §1', 'Besiddelse af Sawed Off', '{\"Pris\":150000,\"Fængselstid\":25,\"Kommentar\":\"Til den som besidder Sawed Off\"}'),
(96, 'Offense', 'Våben & kniv loven', 'VL. §1', 'Besiddelse af Vintage Pistol', '{\"Pris\":100000,\"Fængselstid\":20,\"Kommentar\":\"Til den som besidder Vintage Pistol\"}'),
(97, 'Offense', 'Våben & kniv loven', 'VL. §1', 'Besiddelse af Pistol', '{\"Pris\":100000,\"Fængselstid\":25,\"Kommentar\":\"Til den som besidder Pistol\"}'),
(98, 'Offense', 'Våben & kniv loven', 'VL. §1', 'Besiddelse af SNS Pistol', '{\"Pris\":50000,\"Fængselstid\":20,\"Kommentar\":\"Til den som besidder SNS Pistol\"}'),
(99, 'Offense', 'Våben & kniv loven', 'VL. §1', 'Besiddelse af Stikvåben', '{\"Pris\":5000,\"Fængselstid\":5,\"Kommentar\":\"Til den som besidder Stikvåben\"}'),
(100, 'Offense', 'Våben & kniv loven', 'VL. §1', 'Besiddelse af Ammunition', '{\"Pris\":50,\"Fængselstid\":0,\"Kommentar\":\"Til den som besidder Ammunition (50 pr. stk)\"}'),
(101, 'Offense', 'Våben & kniv loven', 'VL. §1', 'Ulovlig obevaring af våben', '{\"Pris\":10000,\"Fængselstid\":0,\"Kommentar\":\"Til den der obervare våben ulovligt\"}'),
(102, 'Law', 'Ordensbekendtgørelsen', NULL, NULL, '{\"Pris\":0,\"Kommentar\":\"\"}'),
(103, 'Offense', 'Ordensbekendtgørelsen', 'OB. §3', 'Nægter at efter komme politiets anvisninger', '{\"Pris\":5000,\"Kommentar\":\"Hvis der ikke efterkommes anvisninger\"}'),
(104, 'Offense', 'Ordensbekendtgørelsen', 'OB. §3', 'Gadeuorden', '{\"Pris\":7500,\"Kommentar\":\"Hvis folk er til scene for den offentlige orden\"}'),
(105, 'Offense', 'Ordensbekendtgørelsen', 'OB. §3', 'Voldelig optræden', '{\"Pris\":8000,\"Kommentar\":\"Hvis personer er voldelige, uden at skabe et slagsmål med andre\"}'),
(106, 'Offense', 'Ordensbekendtgørelsen', 'OB. §3', 'Voldelig optræden med slagsmål', '{\"Pris\":10000,\"Kommentar\":\"Hvis folk er voldelige og skaber et slagsmål med andre\"}'),
(107, 'Offense', 'Ordensbekendtgørelsen', 'OB. §3', 'Upassende opførsel', '{\"Pris\":5000,\"Kommentar\":\"At være nøgen, seksuelt krænkende m.m\"}'),
(108, 'Offense', 'Ordensbekendtgørelsen', 'OB. §3', 'Ulovlige samkomster', '{\"Pris\":2500,\"Kommentar\":\"Kun til ulovlige Demonstrationer uden tilladelse af Politiet\"}'),
(109, 'Offense', 'Ordensbekendtgørelsen', '', 'Skudsikker vest', '{\"Pris\":7500,\"Kommentar\":\"Gives til personer som ulovligt bærer en skydsikkervest i offentligheden\"}');